name: Run Aerial-VLN Arxiv Papers Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */5 * *"

env:
  GITHUB_USER_NAME: 20bytes
  GITHUB_USER_EMAIL: yuanfang_0512@outlook.com
  DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv
          pip install requests
          pip install pyyaml

      - name: Run daily arxiv
        run: |
          python daily_arxiv.py

      - name: Push updated papers
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🚁 Aerial-VLN Arxiv Daily Auto Update"
          files: README.md docs/cv-arxiv-daily.json docs/cv-arxiv-daily-web.json docs/index.html docs/abstracts
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
